### ISSUE TITLE
epub:type of cover in the section tag - without a matching ARIA role

### ISSUE THREAD

**Issue by flittle8** [daisy/ace-gui#105]
Specifying an epub:type of cover in the section tag - without a matching ARIA role - results in a best-practice warning on the ACE report. (with role="doc-cover"  in the img tag)
(this warning does not occur in EPUBCheck)

```
minor
Best Practice
epub-type-has-matching-role
(via aXe)
"undefined"
cover.xhtml#epubcfi(/4/2)

<section xmlns="http://www.w3.org/1999/xhtml"
xmlns:epub="http://www.idpf.org/2007/ops" epub:type="cover"
aria-labelledby="cover"> 

Element has no ARIA role matching its epub:type
```

**Comment by danielweck** [comment]
Hello, would you be able to provide a test EPUB so that we test at our end with the exact same data set? Thank you! :)

**Comment by flittle8** [comment]
@danielweck turns out the publisher (and us) just needed to update to the latest Ace and problem solved. Apologies! Feel free to delete this ticket :)
