### ISSUE TITLE
next page links scrolled

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ace-gui#115]
I'm getting a scrollbar on the next page links for the tables, regardless of the initial sizing of the application.

<img width="514" alt="truncate" src="https://user-images.githubusercontent.com/1565164/81924519-9cc50c00-95b5-11ea-9871-dd653c5abba6.PNG">

**Comment by danielweck** [comment]
Thank you for your bug reports and screenshots, Matt.
I am closing this as duplicate (the non-responsive user interface, particularly the table report, is a known bug).
https://github.com/daisy/ace-gui/issues/113
