### ISSUE TITLE
vertical scroll position

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ace-gui#116]
Depending on which tab you go to, or even sometimes from page to page within a table, the position of the vertical scroll bar will change from the side of the application to indented from the edge. It would be more user-friendly and less visually jarring if the viewing area were minimally always the available width so it didn't move.

<img width="960" alt="max" src="https://user-images.githubusercontent.com/1565164/81925216-984d2300-95b6-11ea-9d40-326ed3c38e42.PNG">

<img width="960" alt="indent" src="https://user-images.githubusercontent.com/1565164/81925214-984d2300-95b6-11ea-8358-24a999e3091f.PNG">

**Comment by danielweck** [comment]
Thank you for your bug reports and screenshots, Matt.
I am closing this as duplicate (the non-responsive user interface, particularly the table report, is a known bug).
https://github.com/daisy/ace-gui/issues/113
