### ISSUE TITLE
Moderate Violation error Best Practice - unique desc id

### ISSUE THREAD

**Issue by Amkiram** [daisy/ace-gui#136]
I have just created an EPUB that passes the EPUB checker inside calibre with flying colours, and all of the Ace by Daisy checks, except for flagging this one Moderate Best Practice issue:

Moderate | Best Practice | landmark-uniqueVia: aXe | FixedRevisedLilli-3.xhtml#epubcfi(/4[FixedRevisedLilli-3]/6[_idContainer007]/4[desc002])<aside xmlns="http://www.w3.org/1999/xhtml" class="fig-desc" id="desc002">         <p>Titelsida: akvarellmålning av en blå fjällräv på en stig i skenet av norrsken. </p>     </aside>  <aside xmlns="http://www.w3.org/1999/xhtml" class="fig-desc" id="desc003">         <p>bild på förlagets logotyp, "NDIO" med stora, röda bokstäver på svart och vit bakgrund, "kultur och kommunikation" i små vita bokstäver på röd bakgrund under. </p>     </aside>
-- | -- | -- | --

Originally, I figured that the issue was that I titled it "002b", so instead I changed it to a later desc, "024". The issue remained, so I went through the EPUB, first to last xhtml page, and changed all the descs to run in chronological order as they appear in the EPUB, from 001-027. But Ace is STILL flagging this as a fault, on this page only for some reason. There's nothing different about my code here, I have checked and checked. Is this just a bug, or am I doing something wrong? This is my structure on that page, which is returning the "Moderate" Best Practice warning from Ace:

`      <div id="_idContainer007">
			<img class="_idGenObjectAttribute-1 _idGenObjectAttribute-2" src="image/Nr2NorrskensravTitelsida.jpg" alt="illustration" aria-describedby="desc002" />
    <aside class="fig-desc" id="desc002">
        <p>Titelsida: akvarellmålning av en blå fjällräv på en stig i skenet av norrsken. </p>
    </aside>
		</div>
    <div id="_idContainer008">
			<img class="_idGenObjectAttribute-1 _idGenObjectAttribute-2" src="image/logga_kvalitet_tryck.jpg" alt="illustration" aria-describedby="desc003" />
    <aside class="fig-desc" id="desc003">
        <p>bild på förlagets logotyp, "NDIO" med stora, röda bokstäver på svart och vit bakgrund, "kultur och kommunikation" i små vita bokstäver på röd bakgrund under. </p>
    </aside>
    </div>`

**Comment by danielweck** [comment]
`landmark-unique` should be fixed in Ace "next":
https://github.com/daisy/ace/pull/314
Could you please share an EPUB to test with? Many thanks!

**Comment by Amkiram** [comment]
Hi Daniel,
It turns out that if I marked the text visibility as hidden for that
specific alt text, the issue was resolved. It's interesting because in all
the other instances, the alt-text is completely covered by large images,
but that was a very small one, so the text kept running, and I'm wondering
if that's actually why it was flagged by Ace? I did resolve it with this
fix anyway. Ace is such an amazing resource, thank you!

**Comment by danielweck** [comment]
Ah, good to hear you found a workaround. Daisy Ace uses Deque Axe behind the scenes to perform accessibility checks in each individual HTML publication document. Some validation rules depend on the visibility of elements in the page, so perhaps that is the reason for the reported warnings?

**Comment by Amkiram** [comment]
Well, I think it's doing its job very well. It did somehow detect that
there was something "off" with this alt-text, although that isn't exactly
the purpose of the check, but I wonder if it indeed flagged that the
alt-text was visible outside the parameters of the figure it was
describing. I am curious to check if the text-to-speech in Thorium will
still detect and read the desc, as I'm thinking it's only hidden in the
visual sense, but I will have to check later.
Thanks again!
