### ISSUE TITLE
Persist the user settings (and other things?)

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace-gui#14]
Right now the user settings are forgotten when the user closes the app. The settings should be persisted to a user's directory.

**Comment by clapierre** [comment]
I assume this also means window size and position settings as well?  Currently when I make the app larger and exit it opens back up to the original size and center of the screen.

**Comment by danielweck** [comment]
There is a proposed implementation for persistent preferences / user settings, in this Pull Request: https://github.com/daisy/ace-gui/pull/40
