### ISSUE TITLE
Japanese (unicode) characters injected in DAISY Knowledge Base for "go online" link are garbled

### ISSUE THREAD

**Issue by danielweck** [daisy/ace-gui#153]
<img width="1440" alt="AceApp_KB_Japanese" src="https://user-images.githubusercontent.com/625201/152501927-2eee92b5-34ca-4477-8a46-1c2262342fef.png">

<img width="1440" alt="AceApp_KB_English" src="https://raw.githubusercontent.com/daisy/ace-gui/master/doc/AceApp10.png">

**Comment by danielweck** [comment]
Currently, the DAISY Knowledge Base HTML files are for the English language only, and do not declare a `meta` `charset` tag:
https://github.com/daisy/kb/blob/436d88ddd8e161af797e9227259e79a802e91eed/publishing/docs/index.html#L1-L11

**Comment by danielweck** [comment]
Fixed via https://github.com/daisy/ace-gui/commit/a0ca34058bc77db56a8158fe9d05ce51c60a615e

I filed an issue at the DAISY Knowledge Base: https://github.com/daisy/kb/issues/50

**Comment by danielweck** [comment]
Hello @murata2makoto @shunito please read this issue. The fix is implemented here in Ace App, @mattgarrish will probably also implement the fix in the DAISY Knowledge Base soon, but the bugfix will only be available in the next Ace App release.

**Comment by shunito** [comment]
Hello @danielweck 
I recognized the problem. We will figure out how to fix it.
Thank you.

**Comment by shunito** [comment]
Oops, I see that countermeasures are already scheduled to be taken.
Thank you very much.

**Comment by danielweck** [comment]
Yes, the fix is already deployed in the alpha automated release of Ace App:

<img width="1280" alt="Screenshot 2022-02-04 at 09 19 09" src="https://user-images.githubusercontent.com/625201/152517528-43de3068-1a9c-4b0a-a6ed-ca567700353a.png">
