### ISSUE TITLE
Failure to check Content Document in ACE app

### ISSUE THREAD

**Issue by jamie-reece** [daisy/ace-gui#160]
I've come up against the following error message while using the ACE app:

Running Ace on C:\Users\jamie.bowman\Downloads\9781914477171.epub
Error: Failed to check Content Document 'xhtml/copyright.xhtml': did-fail-load: -3 -  - acehttps://0.0.0.0//OEBPS/xhtml/copyright.xhtml?AXE_RUNNER=37 - true - 13 - 1

I've had a look at the manifest and everything looks in order and the referenced file is in the right place.

**Comment by danielweck** [comment]
Hello, are you experiencing this problem with version 1.1.4 ?
https://github.com/daisy/ace-gui/releases/tag/v1.1.4

Would you mind sharing the EPUB privately? daniel.weck@gmail.com

**Comment by truuudy** [comment]
I'm experiencing this issue too with every EPUB. I'm using the most recent version and have un and reinstalled the app many times and nothing is changing. Please help!

**Comment by truuudy** [comment]
Hi Daniel,

Just wanted to check if you had received my email with the EPUB to check on your end.

Thanks,
Trudy

**Comment by danielweck** [comment]
Hello, at your end do you still experience the problem with version `1.1.5`?
https://github.com/daisy/ace-gui/releases/tag/v1.1.5
I have tried the file `9781773383002.epub` ("Exercices d’apprentissage pour la traduction, Servanne Woodward") on my MacOS laptop, everything seems to work.
