### ISSUE TITLE
Adding the ability to edit EPUB accessibility conformance metadata

### ISSUE THREAD

**Issue by gregoriopellegrino** [daisy/ace-gui#165]
Currently, the ability to edit EPUB accessibility metadata is limited to Schema.org data. However, there are other essential accessibility-related details that are expressed as EPUB accessibility conformance metadata. Therefore, I suggest implementing the capability to modify specific accessibility metadata for EPUBs, particularly the fields: conformsTo, certifiedBy, certifierCredential, date (Evaluation date) and certifierReport.

## Proposal

Kindly consider adding these accessibility-specific metadata fields to the editing interface. This enhancement would allow EPUB authors and accessibility managers to provide comprehensive information about accessibility compliance, thereby improving the experience for users with special needs.

## References
EPUB Accessibility 1.1: https://www.w3.org/TR/epub-a11y-11/#sec-conf-reporting

**Comment by danielweck** [comment]
Thank you for reporting this bug, which is now fixed in the `master` branch.
