### ISSUE TITLE
xml:lang errors in Ace and Epub Checker

### ISSUE THREAD

**Issue by msgannon** [daisy/ace-gui#169]
I can't get both Ace and Epub Checker to agree on where the xlm:lang tag should be put in epub 2 in the OPF file. Ace wants it in OPF in "package" but that's only for epub 3, so it throws an error in Epub Checker. Any advice? Many thanks in advance.

**Comment by danielweck** [comment]
Could you please post your comment in this existing issue, thank you: https://github.com/daisy/ace/issues/376
