### ISSUE TITLE
Ace by Daisy reports an invalid serious error about page-source

### ISSUE THREAD

**Issue by jhswift** [daisy/ace-gui#178]
InDesign V20.0 (to be released in 2 weeks time) now including a correctly formatted <meta property> item for the page-source of an ebook with page-lists.
The format is :
    <meta property="pageBreakSource">urn:isbn:9781681727738</meta>
But ACE is still reporting this as an error. It still expects the (now deprecated?) 
   <dc:source id="src">urn:isbn:9781681727738</dc:source>

**Comment by danielweck** [comment]
Related: https://github.com/ways2read/InDesignA11Y/issues/17

Fix: https://github.com/daisy/ace/issues/403

**Comment by jhswift** [comment]
Thanks for this correction. When will ACE be updated to include this fix. The current version is still 1.3.2 it seems
Jim

**Comment by danielweck** [comment]
Hello @jhswift please see https://github.com/daisy/ace/issues/403#issuecomment-2511455257
(I will soon publish a hotfix for this)
