### ISSUE TITLE
Disallow concurrent runs

### ISSUE THREAD

**Issue by clapierre** [daisy/ace-gui#24]
Not sure what happened but I dragged a large file which was taking forever, so I decided to grab a small file and see what would happen while the other was working.
The small file finished and then I believe the large file finished at the same time and all I saw was the result from the large file.

I am testing now, started a large file and while it is working I dropped in a small file which finished quickly before the large file finished.  I am now reviewing the small file's results, but when the first large file finishes I would expect maybe to get a confirmation that I would like to switch to that report?  
What happens is that the small report is blown away and I only see the large report now.
History also doesn't show both reports (separate issue?)

**Comment by rdeltour** [comment]
> I am testing now, started a large file and while it is working I dropped in a small file which finished quickly before the large file finished. I am now reviewing the small file's results, but when the first large file finishes I would expect maybe to get a confirmation that I would like to switch to that report?
> What happens is that the small report is blown away and I only see the large report now.

Right, that's an issue, good catch. Dragging a new file s/b disabled when ace is already running (and there should be an abort command).

> History also doesn't show both reports (separate issue?)

Yes, logged as #3

**Comment by marisademeglio** [comment]
An earlier pre-release version had input disabled while processing. e.g. for the dropzone area:
https://github.com/daisy/ace-gui/blob/react-ui-single-report/src/app/renderer/styles/Sidebar.scss#L22

It should be an easy fix to re-incorporate this.
