### ISSUE TITLE
drag-drop bug over instructions

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ace-gui#33]
The instructions in the startup pane say one way to open an EPUB is to drag and drop a file there, but I tried to do that just now and it wouldn't work.

What I've discovered is that if you drag the file over the title/logo/instructions, Windows seem to go a bit crazy. Instead of the grey-out effect and dashed border that normally appears, a file Copy/Move message starts flickering (see attached image). Then it becomes a bit like the lottery. It seems like if you can time the drop just right to a move message, Ace will run, but if not then you'll get prompted to save the file into the downloads directory. (It's basically the same action you get if you pull a file into a browser window.)

My guess would be that the event capture in that area is a bit wonky because of the clickable links.. So long as the drag starts from outside the center area, everything is fine, but I tend to open folders over top of the app and want to just drag files out of it and release (again, like in the screen grab).

<img width="811" alt="drag" src="https://user-images.githubusercontent.com/1565164/49871322-3f3ef580-fdec-11e8-9c0e-b10c80482499.png">

**Comment by marisademeglio** [comment]
I haven't noticed it on macOS but I'm planning to have a look at drag-n-drop for #24, so I'll check this out too.

**Comment by marisademeglio** [comment]
https://github.com/electron/electron/issues/9794

**Comment by danielweck** [comment]
Related issue: https://github.com/daisy/ace-gui/issues/55

**Comment by danielweck** [comment]
Fixed via https://github.com/daisy/ace-gui/commit/e0604481476d8a073843d81acdf8f5d6357daa94
