### ISSUE TITLE
Processing time

### ISSUE THREAD

**Issue by thiagoeec** [daisy/ace-gui#49]
The GUI is taking 3 times longer than the command line tool (one particular file took me 6,5s to check with the command line tool, and 21s on the GUI; another took 13.3s and 43s; and so on).
Maybe some delay could happen, since it loads the repport inside the application, but this seems like a lot.

*My notebook has i7 7700hq and 16GB or ram. I don't think is hardware limitation.

**Comment by danielweck** [comment]
Hello, are you using this beta release?
https://github.com/daisy/ace-gui/releases/tag/v1.0.0-beta.2

If so, then I have a pretty good idea where this performance discrepancy may be coming from. I will be running some tests to compare timings. Thanks a lot for your feedback!

**Comment by danielweck** [comment]
Possible cause for the performance discrepancy: Electron vs. Puppeteer Axe/Ace runners, concurrent document instances.

Code references:

https://github.com/daisy/ace/blob/34c6e4704aae3793e9e854966428b5b54e246fad/packages/ace-core/src/checker/checker-chromium.js#L128

https://github.com/daisy/ace/blob/34c6e4704aae3793e9e854966428b5b54e246fad/packages/ace-axe-runner-puppeteer/src/index.js#L10

https://github.com/daisy/ace-gui/blob/1bc51e876567cf7a90039e5716666ab4a71f8ea4/src/shared/axe-runner.js#L14

pMap concurrency:
https://github.com/sindresorhus/p-map#concurrency

**Comment by thiagoeec** [comment]
> Hello, are you using this beta release?
> https://github.com/daisy/ace-gui/releases/tag/v1.0.0-beta.2
> 
> If so, then I have a pretty good idea where this performance discrepancy may be coming from. I will be running some tests to compare timings. Thanks a lot for your feedback!

Yes! The last beta available.

**Comment by danielweck** [comment]
This is now fixed (but not yet released). The performance of Ace CLI and Ace GUI are now identical. 

Ace CLI uses a Puppeteer-based Axe runner, whereas Ace GUI uses an Electron one. Both Axe runners are now included in the `ace` (core) repository, and `ace-gui` will be updated soon (in the commit month) to use the improved Axe runner. Both Axe runners can be executed and compared in the `ace` (core) repository, via the command line. There is a pending Pull Request, currently in "Work In Progress" state. More information:
https://github.com/daisy/ace/pull/236#issuecomment-504495913
