### ISSUE TITLE
Localization: when user switches language, already-loaded report is displayed with original locale

### ISSUE THREAD

**Issue by danielweck** [daisy/ace-gui#51]
The data displayed in the GUI report (interactive table) is provided by the report generated by Axe (core), which contains text in the original locale that was active at the time when the Axe (core) command was invoked. Therefore, when the user switches the GUI language, should the app automatically re-run the Axe (core) command, so that the table'd report is updated too?

**Comment by marisademeglio** [comment]
Maybe we could show a message like "the next report you generate will be in your new locale"? Ace supports loading reports from disk, and if we re-run the process just to switch the language, and the source epub has also changed, then we run the risk of altering the displayed report when the user didn't want to. Other idea is to programmatically manipulate the report messages that get shown for each type of violation - that is, if we have low-level access to aXe strings - but what a potentially messy headache for an edge case.

**Comment by danielweck** [comment]
Fixed: the current UX design is to re-run the accessibility evaluation so that the localized strings generated by Axe and Ace core are updated to match the user interface's own language, based on the user locale preference.
Caveat: currently no confirmation dialog, the report is re-generated automatically. I think this is okay for such an edge-case, unlikely to negatively affect anyone.
