### ISSUE TITLE
MacOS: time consuming integrity checks at initial launch

### ISSUE THREAD

**Issue by danielweck** [daisy/ace-gui#52]
... could the launch delay be reduced by using ASAR instead of exploded files? (to be tested!)

Electron's recommended code bundling method is ASAR, but the current build configuration explicitly disables it. Any particular reason why?

https://github.com/daisy/ace-gui/blob/master/package.json#L29

https://github.com/daisy/ace-gui/blob/1bc51e876567cf7a90039e5716666ab4a71f8ea4/package.json#L29

**Comment by marisademeglio** [comment]
Yes, it was causing build issues with puppeteer iirc. @rdeltour may remember more. If we've now switched away from puppeteer, it would be a good idea to use ASAR again.

**Comment by rdeltour** [comment]
@marisa is correct, ASAR was disabled for puppeteer, we should be able to reenable it now.
