### ISSUE TITLE
Drag and drop files one after another

### ISSUE THREAD

**Issue by flittle8** [daisy/ace-gui#55]
Currently I'm unable to drag and drop one file after another. This would be very handy. When I open the App, I'm able to drop in my first EPUB, but when I want to test a new EPUB the only option is to click "Check EPUB" where you're forced to locate the file on your computer and upload that way. It seems like after the first file is dropped in, you're not allowed to drop in further files. This would be a handy thing to be able to do. Cheers

**Comment by danielweck** [comment]
You should be able to drop onto another part of the application UI, you do not need to aim specifically for the large central area (which subsequently gets replaced with the table report).

**Comment by danielweck** [comment]
That being said, the UX is clearly sub-optimal and the drag-drop process can be made more obvious, maybe by creating more emphasis on the drop target during mouse hover.

**Comment by flittle8** [comment]
Hi Daniel - I can drag n drop the 1st file just fine. But I'm not able to drag n drop subsequent files anywhere within the App. I can share a video if that helps?

**Comment by danielweck** [comment]
Is this on Windows, Mac, or Linux? What release / code revision are you testing with? Thank you.

**Comment by flittle8** [comment]
Hi, you just have seen my last message before I deleted it :) I tested it again and it does run another EPUB when it is specifically dropped over the "Check EPUB" text; it won't work if I attempt to drop it elsewhere in the App. I'm on Mac and using version 1.0.0 beta 2

**Comment by danielweck** [comment]
Thank you :)
I will verify this bug.

**Comment by rdeltour** [comment]
Yes, dropping on the Check EPUB button was what’s intended. I agree that the UX should be improved! (eg. highlight the drop area when a drag operation is ongoing, or extend the drop area to the entire UI)

**Comment by danielweck** [comment]
Related issue: https://github.com/daisy/ace-gui/issues/33
