### ISSUE TITLE
Localization: add comments for translators

### ISSUE THREAD

**Issue by nvdaes** [daisy/ace-gui#62]
When translating messages and labels, translators may find useful to know some aspects of the context of those messages. Comments for translators are used in other projects and can help in the translation process. This may avoid extra commits and could improve the quality of translations.
Though the json files are explanatories themselves, for example, translators can infer if a message correspond to a label in a menu and so on, comments could be helpful too.

**Comment by danielweck** [comment]
Hello, and thank you for the Spanish translation of the user interface! I have merged your contribution to the `master` branch.

To test it at your end inside the actual app, please follow the step-by-step instructions in the README in order to build and run the Ace app:
https://github.com/daisy/ace-gui/blob/master/README.md#prerequisites
(the last step you should run is `yarn start:dev` in the "Build, Run, Package" section, no need to try the following ones)

PS: are you a Windows user? (or Linux, or MacOS?)

**Comment by danielweck** [comment]
So, besides trying the localized labels inside a custom build of the Ace App, I agree with you that it can be difficult to translate the strings in isolated / outside of the app context.

Hopefully we can find a solution to this problem, to ease the pain for language contributors.

Thank you very much again for your effort!

**Comment by nvdaes** [comment]
Thank you. I will follow the step by step guide to test. I use Windows with NVDA screen reader. I localized this with a braille display (I am a blind person). I use Notepad Plus Plus for editing files. I am also translating Ace core (the three mentioned files for the command line tool). Also, as a screen reader user, I think we would be grateful if we could use tabs instead of spaces for indentation, since this can be more usable when navigating with the cursor. This is also done in NVDA source code. I built a very small app with electron-forge and used tabs.Thanks a lot. I will share this in case spanish speakers are interested, thanking your attention.

**Comment by danielweck** [comment]
@nvdaes ah, NVDA, now I understand your GitHub ID <smile>

The Ace by DAISY App has not been tested thoroughly with screen readers yet, this is on the priority list for upcoming releases. The development team would really appreciate your feedback. Let me know if you have issues building + running the app.

**Comment by danielweck** [comment]
Regarding tabs vs. spaces: feel free to convert every 4 spaces to tabs in the JSON locale files (a simple search + replace in NotePad++ will do). The JSON files are put through a post-processing step anyway, after Pull Request contributions. This step ensures alphabetical key ordering, and checks for missing keys, as well as unused / redundant keys.

**Comment by nvdaes** [comment]
Hi, unfortunately, I have issues building the app. I wasn't able to do it. About indentation, I read your comment after creating a pull request for Ace adding es localization. If anything else have to be done, I'm quite available until 12 August.
About issues, I get Yarn errors.
About my name on GitHub, yes, I contribute a website about NVDA created by me, and the name is to get the address: nvdaes.github.io.
Thanks for your attention.

**Comment by danielweck** [comment]
I am happy to help you build and run the Ace App, if you would like to. To start, please copy/paste the errors printed in the console (MSDOS / PowerShell, I imagine?). Regards, Daniel

**Comment by nvdaes** [comment]
Hi, firstly, I tell you that I have forked axe-core and make the clean (untranslated yet) es.json file, to work during the next days with a braille display.
About the errors in my Windows console, here is:

yarn install v1.17.3
info No lockfile found.
[1/4] Resolving packages...
error Package "" refers to a non-existing file '"c:\\repos\\ace\\packages\\ace-a
xe-runner-electron"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

c:\repos\ace-gui>yarn clean
yarn run v1.17.3
$ node -e "console.log((new Date(Date.now())).toUTCString())" && rimraf "app/*.j
s" && rimraf "app/yarn.lock" && rimraf "app/node_modules" && rimraf "app/*.js.ma
p" && rimraf "app/*.svg" && rimraf "app/kb" && rimraf "app/package.json" && rimr
af "dist"
Wed, 31 Jul 2019 14:38:04 GMT
"rimraf" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by nvdaes** [comment]
@@danielweck, thanks for your help and attention. I skipped a step, but now I am running the application successfully testing spanish translation.
Not sure if I should open a different issue. For now, most seen translations seems right for me, but the window menu has messages that may not be included in the json file. I may be wrong, but I read the translation a lot of times to be sure. Also, the graphic labelled as "new", identified by underscores, maybe translated and commented. I'm not sure about the purpose of this, since this is not clickable. Seems it is intended to drop files on this. If so, the translation of surrounding test is right.
Thanks

**Comment by danielweck** [comment]
Due to technical limitations, it is not possible to add comments next to each JSON locale property (i.e. `i18next` translation key). Alternatively, it would be difficult / expensive to maintain an external document to map comments with specific JSON entries.

I therefore suggest we close this issue, and instead reference this other one which is about a higher-level translation service that would facilitate language contributions:
https://github.com/daisy/ace/issues/265

**Comment by nvdaes** [comment]
Ok, I we can close this issue. Additionally, I comment that my PR to add spanish translation to axe-core is not merged, but it is approved. I have received a suggestion consisting of translating the words parent and child before roles, i.e.  parent roles and child roles. But I thing this can be writen without translating, just in English, to avoid a longer message or gramatically weird in Spanish without losing precission, considering that when developer documentation is translated some expressions remain in English, and this is intended to be used by peoply who can know the meaning of words like parent and child, used in the DOM, though most expressions and sentences are translated. If you disagree or something, please comment there.

**Comment by danielweck** [comment]
I saw your Axe Pull Requests, thank you very much for this hard work! I agree with your analysis.

**Comment by nvdaes** [comment]
OK. If you want, close the issue yourself. I do not find the button to close with iPhone now. I can do it later from computer, anyway.

**Comment by danielweck** [comment]
I have already closed it <smile>
