### ISSUE TITLE
On Mac dragging a file into App does not work

### ISSUE THREAD

**Issue by clapierre** [daisy/ace-gui#66]
V1.0.0 rc1 

When I drag an EPUB onto the ACE Logo on the App a + sign appears as if it will accept the file and start processing it, but once I let go, nothing happens.

Only using the + or clicking on the browse link works.

This is on my Mac 10.14

**Comment by clapierre** [comment]
I figured out what I need to do in order to get this drop feature to work.  It seems I need to move the cursor around the app a bit before the screen goes light gray in the app allowing for the successful drop of the EPUB.  But if I just drag the EPUB straight from Finder into the app window it won't accept the EPUB file, I have to shake the mouse and move it around in the center of the app window before I get the gray screen indication to release the EPUB file.

**Comment by clapierre** [comment]
I think this should be looked at still as folks won't know to shake the mouse in order to have it successfully drop into the app.

**Comment by clapierre** [comment]
I can create a video showing this if you need it.

**Comment by mattgarrish** [comment]
Sounds like the issue I reported in https://github.com/daisy/ace-gui/issues/33

(I still have that issue in the latest release, fwiw.)

**Comment by danielweck** [comment]
Duplicate issue: https://github.com/daisy/ace-gui/issues/33

**Comment by danielweck** [comment]
Related issue: https://github.com/daisy/ace-gui/issues/33
