### ISSUE TITLE
Ability to pass a file path via a script then present results in GUI

### ISSUE THREAD

**Issue by CircularKen** [daisy/ace-gui#68]
I would like to be able to pass the path to an EPUB file to ACE GUI using a simple script. The app would then launch and the results would then be shown to the user as normal.

Simple AppleScript example would be:

tell application "Finder"
	set x to choose file
end tell

tell application id "org.daisy.ace"
	open x
end tell

This currently works with the pagina EPUB-checker validation GUI which I see as a comparable kind of tool.

tell application "Finder"
	set x to choose file
end tell

tell application id "de.paginagmbh.epubchecker"
	open x
end tell

**Comment by danielweck** [comment]
Ref:
https://electronjs.org/docs/api/app#event-open-file-macos

**Comment by danielweck** [comment]
Fixed via: https://github.com/daisy/ace-gui/commit/00d4abaea1be8dba714fe6eeb612f945c0906e5c

* Tested with AppleScript, e.g.
```
tell application id "org.daisy.ace"
	open "/PATH/TO/BOOK.epub"
end tell
```
* Tested with "Open with..." from the Finder.
* Tested with EPUB double-click (once file extensions `.epub` and `.epub3` are registered by default with the "Ace By DAISY" app).
* Tested with EPUB drag-drop on "Ace By DAISY" app icon.
* Tested with app currently running, as well as app not running yet.

Note that the current implementation displays a confirmation dialog (Yes/No popup modal) to check the EPUB. This might be annoying, so will have to evaluate UX (was worried about inadvertent double-click, which can launch pretty time-consuming checks).

Also note that if a check is already running, a warning popup dialog is displayed (no interruption of the current check, and no automatic queing: the user has to try again later).
