### ISSUE TITLE
Main top-level system menu file > Check EPUB fails

### ISSUE THREAD

**Issue by danielweck** [daisy/ace-gui#69]
Issue discovered here:
https://github.com/daisy/ace-gui/issues/67

**Comment by danielweck** [comment]
Note that "Rerun Ace" also fails from the top-level system menu, which indicates that only the renderer process is able to launch the checker. I know why, working on a fix.

**Comment by marisademeglio** [comment]
I don't know if these fixes ever made it in; it's a branch I was working on for electron 4 (so no longer active) that also included some menu bug fixes: https://github.com/daisy/ace-gui/commit/b84e876824cb3332d60624af9d2f0bec57be00f6

**Comment by danielweck** [comment]
Marisa, I think the current code reflects the changes you made in the branch.
