### ISSUE TITLE
Window goes blank when switching to Metadata section

### ISSUE THREAD

**Issue by jcalderazi** [daisy/ace-gui#72]
On Ace 1.0.0-rc.1
running on macOS Mojave 10.14.15
When clicking on Metadata option. App goes blank and can't go back. Need to quit and rerun. Still html file works fine on browser. Also any other option works fine.

Anybody else with this behaviour?

**Comment by danielweck** [comment]
Closing this issue for now, but feel free to re-open if you are able to provide an EPUB with which the issue can be reproduced :)
