### ISSUE TITLE
Structure de titres Structure HTML vides

### ISSUE THREAD

**Issue by laudrain** [daisy/ace-gui#77]
in "Structures" tab, empty on "Structure de titres" and "Structure HTML"
From report.json issued with Ace 1.1.1:
`  "outlines": {
    "toc": "<ol xmlns=\"http://www.w3.org/1999/xhtml\">\r\n                <li id=\"navpoint-1\">Couverture</li>\r\n                <li id=\"navpoint-2\">Page de titre</li>\r\n                <li id=\"navpoint-3\">Des mêmes auteurs</li>\r\n                <li id=\"navpoint-4\">Introduction ﻿</li>\r\n                <li id=\"navpoint-5\">Première partie Un empire en\r\n                        piteux état<ol>\r\n                        <li id=\"navpoint-6\">1. À la\r\n                                recherche du temps perdu</li>\r\n                        <li id=\"navpoint-7\">2. M la\r\n                                Maudite</li>\r\n                        <li id=\"navpoint-8\">3. Le\r\n                            choc</li>\r\n                        <li id=\"navpoint-9\">4. À armes\r\n                                égales ?</li>\r\n                        <li id=\"navpoint-10\">5. État\r\n                                stationnaire</li>\r\n                        <li id=\"navpoint-11\">6. Des souris\r\n                                et des hommes</li>\r\n                        <li id=\"navpoint-12\">7. Mort au\r\n                                passage</li>\r\n                    </ol></li>\r\n                <li id=\"navpoint-13\">Deuxième partie Le gilet rouge\r\n                        de la République<ol>\r\n                        <li id=\"navpoint-14\">1. Le meilleur\r\n                                d'entre nous</li>\r\n                        <li id=\"navpoint-15\">2. Pepy le\r\n                                Grand</li>\r\n                        <li id=\"navpoint-16\">3. L'ami des\r\n                                médias</li>\r\n                        <li id=\"navpoint-17\">4. L'impossible\r\n                                réforme</li>\r\n                        <li id=\"navpoint-18\">5. Les\r\n                                ministres passent</li>\r\n                        <li id=\"navpoint-19\">6. Haute\r\n                                fragmentation</li>\r\n                    </ol></li>\r\n                <li id=\"navpoint-20\">Troisième partie La France\r\n                        à deux vitesses<ol>\r\n                        <li id=\"navpoint-21\">1. « Prévenez\r\n                                M. Pepy ! »</li>\r\n                        <li id=\"navpoint-22\">2. La\r\n                                créature a dépassé le créateur</li>\r\n                        <li id=\"navpoint-23\">3. Erreur sur\r\n                                la ligne</li>\r\n                        <li id=\"navpoint-24\">4. Le tout TGV\r\n                                est-il vraiment mort ?</li>\r\n                        <li id=\"navpoint-25\">5. Les\r\n                                « cochons de payeurs » se rebiffent</li>\r\n                        <li id=\"navpoint-26\">6. Lignes\r\n                                à vendre</li>\r\n                        <li id=\"navpoint-27\">7. Gare au\r\n                                gendarme !</li>\r\n                    </ol></li>\r\n                <li id=\"navpoint-28\">Épilogue</li>\r\n                <li id=\"navpoint-29\">Remerciements</li>\r\n                <li id=\"navpoint-31\">Page de copyright</li>\r\n                <li id=\"navpoint-30\">Table</li>\r\n            </ol>",
    "headings": "<ul><li><span class=\"toc-h1\">Des mêmes auteurs</span><li><span class=\"toc-h1\">Introduction</span><li><span class=\"toc-h1\">Première partie</span><li><span class=\"toc-h1\">Un empire en piteux état</span><li><span class=\"toc-h1\">1</span><li><span class=\"toc-h1\">À la recherche du temps perdu</span><ul><li><span class=\"toc-h2\">« Avant quand on voulait être à l’heure,\n        on prenait le train »</span></li></ul></li><li><span class=\"toc-h1\">2</span><li><span class=\"toc-h1\">M la Maudite</span><ul><li><span class=\"toc-h2\">Acte I, juillet 2017</span><li><span class=\"toc-h2\">Acte II, décembre 2017</span><li><span class=\"toc-h2\">Acte III, juillet 2018</span></li></ul></li><li><span class=\"toc-h1\">3</span><li><span class=\"toc-h1\">Le choc</span><ul><li><span class=\"toc-h2\">Le train de 16 h 53</span><li><span class=\"toc-h2\">L’affaire Brétigny</span><li><span class=\"toc-h2\">Une histoire d’éclisse</span></li></ul></li><li><span class=\"toc-h1\">4</span><li><span class=\"toc-h1\">À armes égales ?</span><ul><li><span class=\"toc-h2\">Le pot de terre contre le pot de fer</span></li></ul></li><li><span class=\"toc-h1\">5</span><li><span class=\"toc-h1\">État stationnaire</span><ul><li><span class=\"toc-h2\">Des infrastructures gangrénées</span><li><span class=\"toc-h2\">Obsolescence programmée</span></li></ul></li><li><span class=\"toc-h1\">6</span><li><span class=\"toc-h1\">Des souris et des hommes</span><ul><li><span class=\"toc-h2\">La guérite aux rats</span><li><span class=\"toc-h2\">Dépoussiérage</span></li></ul></li><li><span class=\"toc-h1\">7</span><li><span class=\"toc-h1\">Mort au passage</span><ul><li><span class=\"toc-h2\">Des barrières devenues folles</span><li><span class=\"toc-h2\">À qui la faute ?</span><li><span class=\"toc-h2\">Des dysfonctionnements inexpliqués</span></li></ul></li><li><span class=\"toc-h1\">Deuxième partie</span><li><span class=\"toc-h1\">Le gilet rouge de la République</span><li><span class=\"toc-h1\">1</span><li><span class=\"toc-h1\">Le meilleur d’entre nous</span><ul><li><span class=\"toc-h2\">Grand oral</span><li><span class=\"toc-h2\">Une vie dédiée au train</span><li><span class=\"toc-h2\">Promotion Louise Michel</span><li><span class=\"toc-h2\">Au service de l’État</span><li><span class=\"toc-h2\">Sur les rails</span></li></ul></li><li><span class=\"toc-h1\">2</span><li><span class=\"toc-h1\">Pepy le Grand</span><ul><li><span class=\"toc-h2\">Qu’est-ce qui fait courir Guillaume Pepy ?</span><li><span class=\"toc-h2\">Les réseaux</span><li><span class=\"toc-h2\">L’indispensable M. Pepy</span><li><span class=\"toc-h2\">L’état-major</span></li></ul></li><li><span class=\"toc-h1\">3</span><li><span class=\"toc-h1\">L’ami des médias</span><ul><li><span class=\"toc-h2\">Tout pour la com</span><li><span class=\"toc-h2\">Sa parole est d’or</span></li></ul></li><li><span class=\"toc-h1\">4</span><li><span class=\"toc-h1\">L’impossible réforme</span><ul><li><span class=\"toc-h2\">Où ranger la dette ?</span></li></ul></li><li><span class=\"toc-h1\">5</span><li><span class=\"toc-h1\">Les ministres passent</span><ul><li><span class=\"toc-h2\">Le grand rapprochement</span><li><span class=\"toc-h2\">Le RH077, tout un symbole</span><li><span class=\"toc-h2\">La démission de Pepy</span></li></ul></li><li><span class=\"toc-h1\">6</span><li><span class=\"toc-h1\">Haute fragmentation</span><ul><li><span class=\"toc-h2\">La famille cheminote désunie</span><li><span class=\"toc-h2\">L’entreprise aux mille deux cents filiales</span></li></ul></li><li><span class=\"toc-h1\">Troisième partie</span><li><span class=\"toc-h1\">La France à deux vitesses</span><li><span class=\"toc-h1\">1</span><li><span class=\"toc-h1\">« Prévenez M. Pepy ! »</span><ul><li><span class=\"toc-h2\">14 novembre 2015,dernier jour de test en survitesse</span><li><span class=\"toc-h2\">L’erreur est-elle humaine ?</span><li><span class=\"toc-h2\">« Ni impossible, ni interdit »</span></li></ul></li><li><span class=\"toc-h1\">2</span><li><span class=\"toc-h1\">La créature a dépassé le créateur</span><ul><li><span class=\"toc-h2\">La grande vitesse pour tous</span><li><span class=\"toc-h2\">La fuite en avant</span></li></ul></li><li><span class=\"toc-h1\">3</span><li><span class=\"toc-h1\">Erreur sur la ligne</span><li><span class=\"toc-h1\">4</span><li><span class=\"toc-h1\">Le tout TGV est-il vraiment mort ?</span><li><span class=\"toc-h1\">5</span><li><span class=\"toc-h1\">Les « cochons de payeurs » se rebiffent</span><ul><li><span class=\"toc-h2\">Les communes à la rescousse</span><li><span class=\"toc-h2\">Le ras-le-bol de la périphérie</span></li></ul></li><li><span class=\"toc-h1\">6</span><li><span class=\"toc-h1\">Lignes à vendre</span><ul><li><span class=\"toc-h2\">Aubaine access</span><li><span class=\"toc-h2\">Casse sociale</span></li></ul></li><li><span class=\"toc-h1\">7</span><li><span class=\"toc-h1\">Gare au gendarme !</span><li><span class=\"toc-h1\">Épilogue</span><li><span class=\"toc-h1\">Remerciements</span><li><span class=\"toc-h1\">Table</span></li></ul>",
    "html": "<ol><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>Des mêmes auteurs</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>Introduction</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>Première partie</li><li>Un empire en piteux état</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>1</li><li>À la recherche du temps perdu<ol><li>« Avant quand on voulait être à l’heure,\n        on prenait le train »</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>2</li><li>M la Maudite<ol><li>Acte I, juillet 2017</li><li>Acte II, décembre 2017</li><li>Acte III, juillet 2018</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>3</li><li>Le choc<ol><li>Le train de 16 h 53</li><li>L’affaire Brétigny</li><li>Une histoire d’éclisse</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>4</li><li>À armes égales ?<ol><li>Le pot de terre contre le pot de fer</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>5</li><li>État stationnaire<ol><li>Des infrastructures gangrénées</li><li>Obsolescence programmée</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>6</li><li>Des souris et des hommes<ol><li>La guérite aux rats</li><li>Dépoussiérage</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>7</li><li>Mort au passage<ol><li>Des barrières devenues folles</li><li>À qui la faute ?</li><li>Des dysfonctionnements inexpliqués</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>Deuxième partie</li><li>Le gilet rouge de la République</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>1</li><li>Le meilleur d’entre nous<ol><li>Grand oral</li><li>Une vie dédiée au train</li><li>Promotion Louise Michel</li><li>Au service de l’État</li><li>Sur les rails</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>2</li><li>Pepy le Grand<ol><li>Qu’est-ce qui fait courir Guillaume Pepy ?</li><li>Les réseaux</li><li>L’indispensable M. Pepy</li><li>L’état-major</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>3</li><li>L’ami des médias<ol><li>Tout pour la com</li><li>Sa parole est d’or</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>4</li><li>L’impossible réforme<ol><li>Où ranger la dette ?</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>5</li><li>Les ministres passent<ol><li>Le grand rapprochement</li><li>Le RH077, tout un symbole</li><li>La démission de Pepy</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>6</li><li>Haute fragmentation<ol><li>La famille cheminote désunie</li><li>L’entreprise aux mille deux cents filiales</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>Troisième partie</li><li>La France à deux vitesses</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>1</li><li>« Prévenez M. Pepy ! »<ol><li>14 novembre 2015,dernier jour de test en survitesse</li><li>L’erreur est-elle humaine ?</li><li>« Ni impossible, ni interdit »</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>2</li><li>La créature a dépassé le créateur<ol><li>La grande vitesse pour tous</li><li>La fuite en avant</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>3</li><li>Erreur sur la ligne</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>4</li><li>Le tout TGV est-il vraiment mort ?</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>5</li><li>Les « cochons de payeurs » se rebiffent<ol><li>Les communes à la rescousse</li><li>Le ras-le-bol de la périphérie</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>6</li><li>Lignes à vendre<ol><li>Aubaine access</li><li>Casse sociale</li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>7</li><li>Gare au gendarme !</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>Épilogue</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i><ol><li><i>Untitled ASIDE</i></li></ol></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>Remerciements</li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li><i>Untitled SECTION</i></li></ol></li></ol></li><li><ol><li><i>Untitled BODY</i><ol><li>Table</li></ol></li></ol></li></ol>"
  },
`

**Comment by danielweck** [comment]
Hello Luc, are you able/allowed to share the EPUB publication so we can try to reproduce the bug at our end?

**Comment by danielweck** [comment]
Seems related to issue https://github.com/daisy/ace/issues/263 (now solved, but not yet published in official Ace App release)

**Comment by danielweck** [comment]
Possibly related issue: https://github.com/daisy/ace-gui/issues/76

**Comment by laudrain** [comment]
@danielweck just checked again before sending the EPUB, but could not reproduce it.
Nor with other EPUB files...
Let's close the issue for the moment.

**Comment by danielweck** [comment]
I believe this "random" bug is now fixed, via these code changes in Ace ("random" because very sensitive to execution timing, due to an HTML-loading bug in Electron):
https://github.com/daisy/ace/commit/368f8c3d98f87de9ac5b58e876bc742c2c6b62c7
https://github.com/daisy/ace/commit/dc71e4c517523c5477b6ea52af02157987fa7bbf

Note that this code is from the Electron-based Axe runner implementation available in this Pull Request (which is specifically maintained for the Ace App, not yet merged into the Ace `master` branch):
https://github.com/daisy/ace/pull/236
