### ISSUE TITLE
Publications with .epub3 extension should be supported too (works with Ace CLI)

### ISSUE THREAD

**Issue by danielweck** [daisy/ace-gui#80]
Test EPUBs:
https://standardebooks.org/ebooks/anton-chekhov/short-fiction/constance-garnett/
https://standardebooks.org/ebooks/miguel-de-cervantes-saavedra/don-quixote/john-ormsby

CC @acabal

**Comment by danielweck** [comment]
Culprit code:

https://github.com/daisy/ace-gui/blob/e4688b7b06b2ba857b524171899689e3b2513e00/src/shared/actions/app.js#L28

Context:

https://github.com/daisy/ace-gui/blob/e4688b7b06b2ba857b524171899689e3b2513e00/src/shared/actions/app.js#L26-L44

https://github.com/daisy/ace-gui/blob/e4688b7b06b2ba857b524171899689e3b2513e00/src/shared/actions/app.js#L53-L66

**Comment by danielweck** [comment]
Fixed via: https://github.com/daisy/ace-gui/commit/7ba80ba5ae9511c9d972a6f0866d48935ef80535

**Comment by acabal** [comment]
Fantastic, thanks!
