### ISSUE TITLE
Localization: when the system language is available, set it by default

### ISSUE THREAD

**Issue by nvdaes** [daisy/ace-gui#91]
When the OS locale is set to a language available for the app, such as Spanish, the first time that the program is started, this language should be used by default instead of English, so that people don't need to use preferences to change it.
As a possibility, electron.app.getLocale() perhaps could be used to get the default language from the localize.js, and if a translation exist for this language named "default", then default property would be set to true, else English.

**Comment by danielweck** [comment]
Thank you for reporting this @nvdaes but I am closing your issue in order to eliminate duplicates from the tracker.
