### ISSUE TITLE
Empty report on MacOs 10.11.6

### ISSUE THREAD

**Issue by gregoriopellegrino** [daisy/ace-gui#93]
We downloaded and installed the app on my colleague's computer but, while running correctly, it returns an empty report.

OS X El Capitan (versione 10.11.6)

Could it be the old version of the Mac? In that case, perhaps it's better to include a warning.

If necessary, we can arrange screensharing for debugging.

![unnamed (1)](https://user-images.githubusercontent.com/5065125/69042200-1a3a0600-09f1-11ea-856d-9e6e656c5144.png)
![unnamed](https://user-images.githubusercontent.com/5065125/69042201-1ad29c80-09f1-11ea-9504-6ad7103f7dc0.png)
![unnamed (2)](https://user-images.githubusercontent.com/5065125/69042198-1a3a0600-09f1-11ea-9882-78c33e34cf8d.png)

**Comment by danielweck** [comment]
Hello, what version of Ace App is this?
* If `v1.0.0-rc.1` ( https://github.com/daisy/ace-gui/releases/tag/v1.0.0-rc.1 ), then it might be a known bug.
* If the latest "pre-release" ( https://github.com/daisy/ace-gui/releases ), then it is a new bug.

Could you please share the EPUB file with which you are able to reproduce the bug?
Many thanks!
